RayTracer: Math::Vector3D Class Reference
Math::Vector3D Class Reference
#include <Math3D.hpp>
Public Member Functions
Vector3D ()
Vector3D (double x_, double y_, double z_)
double length () const
double dot (const Vector3D &o) const
Vector3D operator+ (const Vector3D &o) const
Vector3D operator- (const Vector3D &o) const
Vector3D operator* (double s) const
Vector3D operator/ (double s) const
Vector3D & operator+= (const Vector3D &o)
Vector3D & operator-= (const Vector3D &o)
Vector3D & operator*= (double s)
Vector3D & operator/= (double s)
Public Attributes
double x
double y
double z
Detailed Description
Definition at line 13 of file Math3D.hpp.
Constructor & Destructor Documentation
Vector3D() [1/2]
Math::Vector3D::Vector3D ()
Definition at line 10 of file Math3D.cpp.
                       : x(0), y(0), z(0)
{}
References x, y, and z.
Vector3D() [2/2]
Math::Vector3D::Vector3D (double x_, double y_, double z_)
Definition at line 13 of file Math3D.cpp.
: x(x_), y(y_), z(z_) {}
References x, y, and z.
Member Function Documentation
dot()
double Math::Vector3D::dot (const Vector3D & o) const
Definition at line 20 of file Math3D.cpp.
{
    return x * o.x + y * o.y + z * o.z;
}
References Vector3D(), x, y, and z.
length()
double Math::Vector3D::length () const
Definition at line 15 of file Math3D.cpp.
{
    return std::sqrt(x * x + y * y + z * z);
}
References x, y, and z.
operator*()
Math::Vector3D Math::Vector3D::operator* (double s) const
Definition at line 35 of file Math3D.cpp.
{
    return Vector3D(x * s, y * s, z * s);
}
References Vector3D(), x, y, and z.
operator*=()
Math::Vector3D & Math::Vector3D::operator*= (double s)
Definition at line 57 of file Math3D.cpp.
{
    x *= s; y *= s; z *= s;
    return *this;
}
References x, y, and z.
operator+()
Math::Vector3D Math::Vector3D::operator+ (const Vector3D & o) const
Definition at line 25 of file Math3D.cpp.
{
    return Vector3D(x + o.x, y + o.y, z + o.z);
}
References Vector3D(), x, y, and z.
operator+=()
Math::Vector3D & Math::Vector3D::operator+= (const Vector3D & o)
Definition at line 45 of file Math3D.cpp.
{
    x += o.x; y += o.y; z += o.z;
    return *this;
}
References Vector3D(), x, y, and z.
operator-()
Math::Vector3D Math::Vector3D::operator- (const Vector3D & o) const
Definition at line 30 of file Math3D.cpp.
{
    return Vector3D(x - o.x, y - o.y, z - o.z);
}
References Vector3D(), x, y, and z.
operator-=()
Math::Vector3D & Math::Vector3D::operator-= (const Vector3D & o)
Definition at line 51 of file Math3D.cpp.
{
    x -= o.x; y -= o.y; z -= o.z;
    return *this;
}
References Vector3D(), x, y, and z.
operator/()
Math::Vector3D Math::Vector3D::operator/ (double s) const
Definition at line 40 of file Math3D.cpp.
{
    return Vector3D(x / s, y / s, z / s);
}
References Vector3D(), x, y, and z.
operator/=()
Math::Vector3D & Math::Vector3D::operator/= (double s)
Definition at line 63 of file Math3D.cpp.
{
    x /= s; y /= s; z /= s;
    return *this;
}
References x, y, and z.
Member Data Documentation
x
double Math::Vector3D::x
Definition at line 15 of file Math3D.hpp.
y
double Math::Vector3D::y
Definition at line 15 of file Math3D.hpp.
z
double Math::Vector3D::z
Definition at line 15 of file Math3D.hpp.
The documentation for this class was generated from the following files:
include/Math3D.hpp
src/Math3D.cpp